### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by dvdobrovolskiy** [joeaudette/cloudscribe.Web.Pagination#11]
I used cloudscribe.Web.Pagination in my new project instead of telerik grid as I needed less bulky solution and I do not need filters and other tons of options provided by kendo grid. but what I do need is a proper search option. I see demos and there is some options like filter by category. so

Is it possible to filter result by string containing key words like product name, category name, some other things all together (sort of like autocomplete works)? I mean is it possible without forking project but using current functionality or is it might be possible for you to add suck a feature?

Dima

**Comment by joeaudette** [comment]
filtering should happen at data query retrieval time, pagination is not related to filtering. I'm doing search with various parameters in my cloudscribe.Core project along with using this pager. the pager just has to know how many total items so I have a corresponding count query for every search query in order to tell the pager the total items.
things should be designed with separation of concerns, filtering and paging are different concerns

**Comment by dvdobrovolskiy** [comment]
tnks will try to do that. will be grate if it possible to do via ajax

**Comment by joeaudette** [comment]
you just need to make sure the asp-route-* params set on the pager includes the needed route params that you use in the form post for the search so that when they ajax page over the search results all the right params are passed
