### ISSUE TITLE
async requests

### ISSUE THREAD

**Issue by dvdobrovolskiy** [joeaudette/cloudscribe.Web.Pagination#12]
Is any chance an option to use async requests? like asp.net core rc2 standard template

        public async Task<IActionResult> Index()
        {
            return View(await _context.Reason.ToListAsync());
        }

_context.Reason.ToPagedList(0, DefaultPageSize) does not have ToListAsync method

**Comment by joeaudette** [comment]
honestly PagedList is a completely separate thing from the pagertaghelper, pagertaghelper does not depend on PagedList and really the only reason pagedlist exists in this library is because it was based on [Martijn Boland's MVCPaging project](https://github.com/martijnboland/MvcPaging) and it had a pagedlist which I copied. PagedList is kind of a hack for when you are retrieving more than a page of data but want to do paging against the result set.

I don't use PagedList at all myself and don't really care to try to support it or update it. There are other implementations of PagedList out there that anyone could also use, so it is completely independent from the pagertaghelper. From a brief search I found [this pagedlist](https://github.com/kpi-ua/X.PagedList) which has async support, but not sure it has a compatible nuget for aspnetcore rc2. But you can search and maybe find a better compatible one, I did not spend much time looking. Or if anyone is interested in implementing that and submitting a pull request I'm open to that as well.

I do async methods to get data in my own use of pagertaghelper, and I just return one page of data at a time from the database so I don't need any pagedlist. 

maybe could do it like this:

    public async Task<IActionResult> Index()
    {
	    var data = await _context.Reason.ToListAsync();
        return View(data.ToPagedList(0, DefaultPageSize));
    }

but again that looks like it returns more than a page of data and then uses pagedlist to page over it which is what PagedList is for but also why PagedList is a hack compared to just return a page of data from the database using .Skip .Take etc

**Comment by joeaudette** [comment]
only thing I've ever used PagedList for is the demo pages because it was convenient to make a demo without any database, and much of the demo code was also copied from Martijn's project and that is how PagedList ended up in this project. I never use that PagedList in my own projects, I only use the taghelpers

**Comment by dvdobrovolskiy** [comment]
hm, sorry I a bit confused here. if you dont use PagedList what you use in your Pagination project? I mean then you retrieve data from DB.

**Comment by joeaudette** [comment]
you can see an example [here a controller](https://github.com/joeaudette/cloudscribe/blob/master/src/cloudscribe.Core.Web/Controllers/UserAdminController.cs) which has methods for user admin and paging of users with search, and the [corresponding partial view here](https://github.com/joeaudette/cloudscribe/blob/master/src/cloudscribe.Core.Web/Views/Sys/UserAdmin/UserGridPartial.cshtml)

as I said the use of PagedList in the pager demo pages was mainly because I copied existing demo pages and that makes it easy to have demo without any db, you just make a big list of data and use pagedlist to page over it. but again PagedList is only for if you already retrieved (or created as in the demo code) more than a page of data and now you want to page over that data. It is much better to not use PagedList and only retrieve data one page at a time from the db. PageTagHelper doesn't know about PagedList at all.

**Comment by joeaudette** [comment]
not that in the example I linked, you will see model.Paging.* properties being set, in that model Paging is an instance of [PaginationSettings](https://github.com/joeaudette/cloudscribe.Web.Pagination/blob/master/src/cloudscribe.Web.Pagination/PaginationSettings.cs) it is simply a model to pass settings on to the pagertaghelper

**Comment by joeaudette** [comment]
this makes me think I should get rid of PagedList and not use it in the demos because it makes people think they need to use that when in fact it is best not to

**Comment by joeaudette** [comment]
fyi, I've reworked the demo app and removed all use of PagedList from the demo so as not to encourage use of that

**Comment by dvdobrovolskiy** [comment]
Many tnks. checking
