### ISSUE TITLE
Add option to turn on [ render if only 1 page ]

### ISSUE THREAD

**Issue by John0King** [joeaudette/cloudscribe.Web.Pagination#13]
Add option to turn on [ render if only 1 page ].

It's a good idea to not render if only 1 page, but when you test the page , that don't show anything,it hard to find out  that page is paged or not

I think it's a good idea to add a global setting in `Startup` class, when the `Environment` is `Development`  turn this on .

**Comment by joeaudette** [comment]
personally I can't see any good reason to ever show an empty (ul) pager, showing that doesn't prove paging is working and empty ul elements are actually not valid html. I certainly do not want to add any global variables that do that, then I will get bug reports from everyone using it in development. 

but since you want to be able to show an empty pager I have just now added a setting that you can make on the pager itself

    cs-suppress-empty-pager="false"

the default is true so if you want to show it when empty then you could set that false using your own global variable or whatever logic you choose. I just published the nuget for version 1.0.1-beta7 which has this new setting just for you

**Comment by John0King** [comment]
Thank you so much
